### ISSUE TITLE
admin users don't work on globus

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#145]
This is how the ocean staging.yml secrets look

```
pangeo:
  jupyterhub:
    proxy:
      secretToken: XXX
    auth:
      type: globus
      globus:
        clientId: "XXX"
        clientSecret: "XXX"
        callbackUrl: "https://staging.ocean.pangeo.io/hub/oauth_callback"
        identityProvider: "orcid.org"
        admin:
          access: true
          users:
            - 0000-0001-7479-8439 # Joe Hamman
            - 0000-0001-5999-4917 # Ryan Abernathey
            - 0000-0003-4004-4553 # Raphael Dussin
```

The hub startup log says
```
Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
Loading extra config: customPodHook
Loading extra config: profile_list
[I 2019-03-07 00:08:39.981 JupyterHub app:1673] Using Authenticator: oauthenticator.globus.GlobusOAuthenticator-0.8.1
[I 2019-03-07 00:08:39.981 JupyterHub app:1673] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2019-03-07 00:08:39.981 JupyterHub app:1016] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[W 2019-03-07 00:08:40.079 JupyterHub app:1131] JupyterHub.hub_connect_port is deprecated as of 0.9. Use JupyterHub.hub_connect_url to fully specify the URL for connecting to the Hub.
[W 2019-03-07 00:08:40.081 JupyterHub app:1173] No admin users, admin interface will be unavailable.
[W 2019-03-07 00:08:40.082 JupyterHub app:1174] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2019-03-07 00:08:40.082 JupyterHub app:1201] Not using whitelist. Any authenticated user will be allowed.
```

Note the **No admin users**. What's wrong?
