### ISSUE TITLE
[GCP] Node pool configuration

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cloud-federation#264]
I've been working on a setup for better handling workloads and scheduling on our GCP clusters. I've come up with a system that is general enough to work anywhere while still giving us fine grained control of which jobs land in specific node pools. The basics are as follows...

A pangeo k8s cluster has 3 or more node pools:

A. A `core-pool`. This is relatively small and holds the Jupyterhub and related utilities. This does not autoscale as it is intended to only hold the persistent services in our cluster.
B. One or more `jupyter-pool`s. This is an autoscaling node pool intended to serve all single-user Jupyter sessions.
C. One or more `dask-pool`s. This is an autoscaling node pool that uses preemptable instances. It is intended to only hold dask workers. 

Nothing new yet. What I've added is a series of labels/taints/tolerations that help herd pods into the right place. For this to work, all the services need to set corresponding affinities/tolerations. I've linked to each of these below:

- `core-pool`:
  - label: `hub.jupyter.org/node-purpose=core` ([link](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#scheduling-corepods))
- `jupyter-pool`: 
  - taint: `hub.jupyter.org/dedicated=user:NoSchedule` ([link](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#singleuser-extratolerations))
  - label: `hub.jupyter.org/node-purpose=user` ([link](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#scheduling-userpods))
- `dask-pool`:
  - taint: `k8s.dask.org/dedicated=worker:NoSchedule` ([link](https://kubernetes.dask.org/en/latest/#deployment-details))
  - label: `k8s.dask.org/node-purpose=worker` ([WIP-link](https://github.com/dask/dask-kubernetes/pull/147))

So what does this give us that we don't have now...Well, a few things:

1. A way to keep the hub pods in the core pool, because sometimes they wonder
2. A way to keep dask pods out of the jupyter-pool, because default scheduling doesn't mind putting dask pods in a non-preemtable pool
3. A way to direct scheduling without relying on the user to properly configure their dask pods. 

-----

Finally, a GCP recipe for adding these node pools: 

```bash
# core-pool
core_machine_type="n1-standard-2"
core_labels="hub.jupyter.org/node-purpose=core"
gcloud container node-pools create core-pool \
    --cluster=${cluster_name} \
    --machine-type=${core_machine_type} \
    --zone=${zone} \
    --num-nodes=3 \
    --node-labels ${core_labels}

# jupyter-pool-n1-highmem-16
jupyter_machine_type="n1-highmem-16"
jupyter_taints="hub.jupyter.org_dedicated=user:NoSchedule"
jupyter_labels="hub.jupyter.org/node-purpose=user"
gcloud container node-pools create jupyter-pool \
    --cluster=${cluster_name} \
    --machine-type=${jupyter_machine_type} \
    --disk-type=pd-ssd \
    --zone=${zone} \
    --num-nodes=0 \
    --enable-autoscaling --min-nodes=0 --max-nodes=10 \
    --node-taints ${jupyter_taints} \
    --node-labels ${jupyter_labels}


# dask-pool
dask_machine_type="n1-highmem-4"
dask_taints="k8s.dask.org_dedicated=worker:NoSchedule"
dask_labels="k8s.dask.org/node-purpose=worker"
gcloud container node-pools create dask-pool \
    --cluster=${cluster_name} \
    --preemptible \
    --machine-type=${dask_machine_type} \
    --disk-type=pd-ssd \
    --zone=${zone} \
    --num-nodes=0 \
    --enable-autoscaling --min-nodes=0 --max-nodes=10 \
    --node-taints ${dask_taints} \
    --node-labels ${dask_labels}
```

**Comment by jhamman** [comment]
Okay, I've been testing this out in a real cluster and I'm seeing some unexpected behavior. Below I'm including the specs for both the `jupyter-pool` and a single-user jupyter pod. The jupyter pool is configured as described above and the user pod is configured like any other in this repo (without an explicit nodeSelector or anything like that). 

The problem: The single user pod isn't scheduled in the jupyter-pool, instead its placed in the `temp-dask-pool`, a pool without any taints and a single label (`k8s.dask.org/node-purpose: worker`).

My questions: How do we diagnose the reasoning behind scheduling choices that kubernetes makes? Do the labels/taints that I have implemented look right? 

cc @consideRatio, @yuvipanda, @jacobtomlinson 

##### `jupyter-pool` (node pool)
```yaml
# gcloud container node-pools describe --cluster $cluster_name jupyter-pool
autoscaling:
  enabled: true
  maxNodeCount: 10
config:
  diskSizeGb: 100
  diskType: pd-standard
  imageType: COS
  labels:
    hub.jupyter.org/node-purpose: user
  machineType: n1-highmem-16
  oauthScopes:
  - https://www.googleapis.com/auth/devstorage.read_only
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  - https://www.googleapis.com/auth/service.management.readonly
  - https://www.googleapis.com/auth/servicecontrol
  - https://www.googleapis.com/auth/trace.append
  serviceAccount: default
  taints:
  - effect: NO_SCHEDULE
    key: hub.jupyter.org_dedicated
    value: user
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/pangeo-181919/zones/us-central1-b/instanceGroupManagers/gke-dev-pangeo-io-cluste-jupyter-pool-6bc2c317-grp
management:
  autoRepair: true
maxPodsConstraint:
  maxPodsPerNode: '110'
name: jupyter-pool
podIpv4CidrSize: 24
selfLink: https://container.googleapis.com/v1/projects/pangeo-181919/zones/us-central1-b/clusters/dev-pangeo-io-cluster/nodePools/jupyter-pool
status: RUNNING
version: 1.11.8-gke.6
```

##### `jupyter-jhamman` (pod)
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    hub.jupyter.org/username: jhamman
  creationTimestamp: 2019-05-07T03:35:18Z
  labels:
    app: jupyterhub
    chart: jupyterhub-0.9-8ed2f81
    component: singleuser-server
    heritage: jupyterhub
    hub.jupyter.org/network-access-hub: "true"
    release: hydro-prod
  name: jupyter-jhamman
  namespace: hydro-prod
  resourceVersion: "50053730"
  selfLink: /api/v1/namespaces/hydro-prod/pods/jupyter-jhamman
  uid: 22732911-7079-11e9-af2c-42010a800170
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
        weight: 100
...
  nodeName: gke-dev-pangeo-io-clus-temp-dask-pool-8bacb14c-zl84
  priority: 0
  priorityClassName: hydro-prod-default-priority
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 100
    runAsUser: 1000
  serviceAccount: daskkubernetes
  serviceAccountName: daskkubernetes
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: hub.jupyter.org/dedicated
    operator: Equal
    value: user
  - effect: NoSchedule
    key: hub.jupyter.org_dedicated
    operator: Equal
    value: user
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```
