### ISSUE TITLE
Many 'Evicted' hub pods

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#274]
We recently ran into an issue with our NASA deployment that I'll document here for others. We were seeing many pods being 'Evicted' without being deleted:

`kubectl get pods --namespace nasa-staging -o wide`
```
autohttps-5c855b856b-29qn6   0/2       Evicted   0          33h       <none>           ip-192-168-42-166.ec2.internal   <none>
autohttps-5c855b856b-4kmkw   0/2       Evicted   0          4h52m     <none>           ip-192-168-42-166.ec2.internal   <none>
autohttps-5c855b856b-566mt   0/2       Evicted   0          13d       <none>           ip-192-
.
.
.
hub-b55dd58f7-6nqpn          0/1       Evicted   0          10h       <none>           ip-192-168-42-166.ec2.internal   <none>
hub-b55dd58f7-9tw7t          0/1       Evicted   0          10h       <none>           ip-192-168-42-166.ec2.internal   <none>
```

As far as we can tell, this was due to the default local disk size being too small (our EBS volume for the hub node was just 10Gb. This was filling up, and causing Evictions (see https://github.com/kubernetes/kubernetes/issues/71869 and https://github.com/kubernetes/autoscaler/issues/1049)

`df -h`
```
[ec2-user@ip-192-168-42-166 ~]$ df -h
Filesystem                                 Size  Used Avail Use% Mounted on
devtmpfs                                   3.8G     0  3.8G   0% /dev
tmpfs                                      3.8G     0  3.8G   0% /dev/shm
tmpfs                                      3.8G  896K  3.8G   1% /run
tmpfs                                      3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/nvme0n1p1                              10G  8.5G  1.6G  85% /
```

We increased the disk size to 100Gb to match GKE clusters and the problem seems solved. We can be explicit about the default volume size when launching nodegroups with eksctl (https://github.com/weaveworks/eksctl/issues/780)

**Comment by errordeveloper** [comment]
@scottyhq please let me know if you need help here, slack.weave.works is probably the best place.

**Comment by scottyhq** [comment]
closing. our eksctl hub node configuration looks like this currently:
```
nodeGroups:
  - name: core
    instanceType: m5.large
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    labels:
      node-role.kubernetes.io/core: core
      hub.jupyter.org/node-purpose: core
    ami: auto
    amiFamily: AmazonLinux2
    ssh:
      publicKeyPath: eks-pangeo-us-west-2.pub
    iam:
      withAddonPolicies:
        autoScaler: true
        efs: true
```
