### ISSUE TITLE
use mixed nodegroups with spot instances on AWS clusters

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#298]
nasa and icesat2 hubs running on AWS are still using on-demand instances for dask workers. this is a perfect use-case for spot instances. we might be able to keep the current configurations in this repo, and just modify our nodegroups on the cluster: 

https://github.com/pangeo-data/ACCESS_K8S/issues/5

also related: https://github.com/pangeo-data/pangeo-cloud-federation/issues/188

**Comment by scottyhq** [comment]
it's a bit unclear if this works w/ cluster and autoscalers 1.13. Might need to wait until 1.14. Watch https://github.com/weaveworks/eksctl/issues/839 and https://github.com/weaveworks/eksctl/issues/1012#issuecomment-511491537

**Comment by scottyhq** [comment]
Kubernetes 1.14 - https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-now-supports-kubernetes-version-1-14/ (and autoscaler 1.14) made some fixes so that now autoscaling mixed spot instances from 0 works as expected https://github.com/kubernetes/autoscaler/issues/2246#issuecomment-520129217 (edited). I just tested this config on the aws pangeo binderhub and things seem to be working well.

```
  - name: user-spot
    privateNetworking: true
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    instancesDistribution:
      #maxPrice: 0.017 #default to max price = on demand price
      instanceTypes:
        - m5.2xlarge
        - m4.2xlarge # At least two instance types should be specified
      spotInstancePools: 2
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0 # all spot
    volumeSize: 100
    volumeType: gp2
    labels:
      node-role.kubernetes.io/user: user
      hub.jupyter.org/node-purpose: user
    taints:
      hub.jupyter.org/dedicated: 'user:NoSchedule'
    tags:
        k8s.io/cluster-autoscaler/node-template/label/hub.jupyter.org/node-purpose: user
        k8s.io/cluster-autoscaler/node-template/taint/hub.jupyter.org/dedicated: 'user:NoSchedule'
    ami: auto
    amiFamily: AmazonLinux2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::XXXXXXXXXXX:policy/pangeo-data-s3
      withAddonPolicies:
        autoScaler: true
```

If we upgrade AWS clusters and nodegroups to 1.14 one drawback is that we'd be ahead of zero2jupyterhub k8s testing (through 1.13) https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/.travis.yml#L20. So maybe once https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1422 is merged, we make the upgrade? Thoughts @jhamman and @rsignell-usgs ?
