### ISSUE TITLE
Correct Pod Security Policies (securityContext) for singleuser jupyter pods and containers

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-cloud-federation#581]
Our JupyterHub images are meant to run as a non-root jovyan user with uid:gid 1000:1000 (https://github.com/pangeo-data/pangeo-stacks-dev/blob/fc42935aa20003890d8aab48ef6475e7e10e82fb/base-image/Dockerfile#L24), but currently containers run with the following securityContext: 

(abbreviated)
```
kind: Pod
  name: jupyter-scottyhq
spec:
  containers:
  - args:
    - jupyterhub-singleuser
    - --ip=0.0.0.0
    - --port=8888
    - --NotebookApp.default_url=/lab
    image: uwhackweeks/icesat2:latest
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: notebook
    ports:
    - containerPort: 8888
      name: notebook-port
      protocol: TCP
    securityContext:
      runAsGroup: 0
      runAsUser: 1000
  securityContext:
    fsGroup: 100
  serviceAccount: daskkubernetes
```

Based on discussion for binderhub config https://github.com/pangeo-data/pangeo-binder/pull/136 I think we should change this to
```
  containers:
  - args:
    - jupyterhub-singleuser
    ...
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
  securityContext:
    fsGroup: 1000
```
These can be set under values.yaml here, but I'm not sure about `runAsGroup`? https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/2d435d64d4978380f68a1bda185add4376c29272/jupyterhub/values.yaml#L188-L189

cc @consideRatio , @jhamman , @tjcrone
