### ISSUE TITLE
Bump to Dask Gateway 0.7.1

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#584]
Dask-Gateway 0.7.1 made some changes to the helm configuration from 0.6.1. I'd like to get all the hubs moved over to 0.7.1 as a group.

We did this on the binders at https://github.com/pangeo-data/pangeo-binder/pull/139.

IIUC, we'll need to

1. Bump dask-gateway at https://github.com/pangeo-data/helm-chart/blob/6749ba1276f0eacc68bf23be4224504403cd2e99/pangeo/Chart.yaml#L12-L14
2. Depend on the new helm chart at https://github.com/pangeo-data/pangeo-cloud-federation/blob/d927da6594035b5455d565e564418e937ce893e7/pangeo-deploy/Chart.yaml#L8
3. Bump all the dask-gateway in the `environment.yaml`s (e.g. https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/dev/image/binder/environment.yml).

cc @scottyhq, @tjcrone.

**Comment by scottyhq** [comment]
@TomAugspurger  testing on staging.aws-uswest2.pangeo.io I'm seeing the following traceback for new_cluster()

```pytb
/srv/conda/envs/notebook/lib/python3.7/site-packages/aiohttp/client_reqrep.py in raise_for_status(self)
    944                 status=self.status,
    945                 message=self.reason,
--> 946                 headers=self.headers)
    947 
    948     def _cleanup_writer(self) -> None:

ClientResponseError: 502, message='Bad Gateway', url=URL('https://staging.aws-uswest2.pangeo.io/services/dask-gateway/api/v1/clusters/')
```

With lots of repeat tracebacks in the logs:
```
[E 2020-04-28 21:38:35.249 KubeController] Error in cluster informer, retrying...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 161, in run
    initial = await method(**self.method_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dask_gateway_server/backends/kubernetes/utils.py", line 59, in func
    return await method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/api_client.py", line 166, in __call_api
    _request_timeout=_request_timeout)
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 191, in GET
    query_params=query_params))
  File "/opt/conda/lib/python3.7/site-packages/kubernetes_asyncio/client/rest.py", line 181, in request
    raise ApiException(http_resp=r)
kubernetes_asyncio.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: <CIMultiDictProxy('Audit-Id': '87204ab9-d515-4c14-b1f1-16dab15c9b64', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 28 Apr 2020 21:38:35 GMT', 'Content-Length': '19')>
HTTP response body: 404 page not found
```


Hub logs show:
```
[I 2020-04-28 21:51:41.965 JupyterHub app:2580] Adding external service dask-gateway at http://traefik-icesat2-staging-dask-gateway.icesat2-staging
[I 2020-04-28 21:51:42.554 JupyterHub log:174] 200 GET /hub/api/users (cull-idle@127.0.0.1) 86.52ms
[I 2020-04-28 21:51:42.832 JupyterHub log:174] 200 GET /hub/health (@192.168.98.161) 1.17ms
[E 2020-04-28 21:51:43.046 JupyterHub app:2611] Cannot connect to external service dask-gateway at http://traefik-icesat2-staging-dask-gateway.icesat2-staging. Is it running?
[I 2020-04-28 21:51:43.049 JupyterHub proxy:320] Checking routes
```

and traefik log:
```
➜  ~ kubectl logs -n icesat2-staging traefik-icesat2-staging-dask-gateway-5d867d7785-8w7s6
time="2020-04-28T21:51:37Z" level=info msg="Configuration loaded from flags."
time="2020-04-28T21:51:38Z" level=error msg="subset not found for icesat2-staging/api-icesat2-staging-dask-gateway" ingress=api-icesat2-staging-dask-gateway namespace=icesat2-staging providerName=kubernetescrd
```

**Comment by scottyhq** [comment]
seems I forgot to run `kubectl apply -f https://raw.githubusercontent.com/dask/dask-gateway/0.7.1/resources/helm/dask-gateway/crds/daskclusters.yaml`

**Comment by scottyhq** [comment]
the logs look good but am now seeing the following traceback and unsure how to debug. I don't see obvious error in the logs, i suspect I have some URL wrong in here https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/icesat2/config/staging.yaml#L16. @consideRatio and tips?

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in new_cluster(self, cluster_options, shutdown_on_close, **kwargs)
    623             cluster_options=cluster_options,
    624             shutdown_on_close=shutdown_on_close,
--> 625             **kwargs,
    626         )
    627 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, auth, cluster_options, shutdown_on_close, asynchronous, loop, **kwargs)
    780             shutdown_on_close=shutdown_on_close,
    781             asynchronous=asynchronous,
--> 782             loop=loop,
    783         )
    784 

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _init_internal(self, address, proxy_address, auth, cluster_options, cluster_kwargs, shutdown_on_close, asynchronous, loop, name)
    872             self.status = "starting"
    873         if not self.asynchronous:
--> 874             self.gateway.sync(self._start_internal)
    875 
    876     @property

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in sync(self, func, *args, **kwargs)
    326             )
    327             try:
--> 328                 return future.result()
    329             except BaseException:
    330                 future.cancel()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_internal(self)
    886             self._start_task = asyncio.ensure_future(self._start_async())
    887         try:
--> 888             await self._start_task
    889         except BaseException:
    890             # On exception, cleanup

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _start_async(self)
    900             self.status = "starting"
    901             self.name = await self.gateway._submit(
--> 902                 cluster_options=self._cluster_options, **self._cluster_kwargs
    903             )
    904         # Connect to cluster

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _submit(self, cluster_options, **kwargs)
    511             options = self._config_cluster_options()
    512             options.update(kwargs)
--> 513         resp = await self._request("POST", url, json={"cluster_options": options})
    514         data = await resp.json()
    515         return data["name"]

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_gateway/client.py in _request(self, method, url, json)
    389 
    390             if resp.status in {404, 422}:
--> 391                 raise ValueError(msg)
    392             elif resp.status == 409:
    393                 raise GatewayClusterError(msg)

ValueError: 404 page not found
```

**Comment by consideRatio** [comment]
@scottyhq I think the failure relates to the configuration of addresses, and, I think it is your environment variables. In a functional setup, this is how I have things configured.

```yaml
# jupyterhub config.yaml
# (note: running jupyterhub as a subchart)
jupyterhub:
  hub:
    services:
      # ref: https://jupyterhub.readthedocs.io/en/stable/reference/services.html#properties-of-a-service
      dask-gateway:
        apiToken: redacted-X
        # url will make jupyterhub configure its own proxy to route
        # "/services/dask-gateway" to this destination.
        url: http://traefik-dask-gateway.dask-gateway
```

```yaml
# /etc/dask/gateway.yaml - mounted through a configmap on user pods
# I figure you can use equivalent environment variables instead
gateway:
  proxyToken: redacted-Y

  # don't set this to https
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  public-address: https://jupyter.example.com/services/dask-gateway

  auth:
    type: jupyterhub
    jupyterhub:
      # A JupyterHub api token for dask-gateway to use. See
      # https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub.
      apiToken: redacted-X
      apiUrl: http://hub.jupyterhub:8081/hub/api
```

**Comment by scottyhq** [comment]
Thanks @consideRatio , that does look a bit different from our current model setup here:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/2a8f23eb8a9bc06e4d4187a19a32524c0f0dd6f4/deployments/dev/config/staging.yaml#L19-L27

And here https://github.com/pangeo-data/pangeo-cloud-federation/blob/2a8f23eb8a9bc06e4d4187a19a32524c0f0dd6f4/pangeo-deploy/values.yaml#L44-L50

**Comment by consideRatio** [comment]
Something like this is good for 0.7.1 i think.

```yaml
 singleuser: 
   extraEnv: 
     DASK_GATEWAY__ADDRESS: "http://traefik-dev-staging-dask-gateway.dev-staging"
     DASK_GATEWAY__PUBLIC_ADDRESS: "https://staging.hub.pangeo.io/services/dask-gateway"
 hub: 
   services: 
     dask-gateway: 
       # This makes the gateway available at ${HUB_URL}/services/dask-gateway 
       url: "http://traefik-dev-staging-dask-gateway.dev-staging" 
```

**Comment by scottyhq** [comment]
@TomAugspurger - can you confirm your current config for `dev` is working? If so perhaps there is some difference in the cluster level config? I'm pretty sure we are in a 'deployment succeed' but dask gateway is not actually working state.

I'm confused because we've been successfully using the PROXY_ADDESS on binderhub, which is working...
https://github.com/pangeo-data/pangeo-binder/blob/c58c869045b8f1374825ad01dcbf360bdc57a77b/deploy-aws/staging.yaml#L72-L87
```
    singleuser:
      serviceAccountName: pangeo
      extraEnv:
        DASK_GATEWAY__ADDRESS: "https://hub.staging.aws-uswest2-binder.pangeo.io/services/dask-gateway/"
        DASK_GATEWAY__PROXY_ADDRESS: "gateway://traefik-staging-dask-gateway.staging:80"

      services:
        dask-gateway:
          # This makes the gateway available at ${HUB_URL}/services/dask-gateway
          url: http://traefik-staging-dask-gateway.staging
```
A major difference there seems to be that `traefik-staging-dask-gateway` is a LoadBalancer with an external IP. But the only external IP in a hub namespace is `proxy-public`...

```
(jupyterhub)                        
NAME                                   TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                      AGE
api-icesat2-staging-dask-gateway       ClusterIP      10.100.119.69    <none>                                                                    8000/TCP                     25h
hub                                    ClusterIP      10.100.2.76      <none>                                                                    8081/TCP                     397d
proxy-api                              ClusterIP      10.100.154.18    <none>                                                                    8001/TCP                     397d
proxy-http                             ClusterIP      10.100.29.251    <none>                                                                    8000/TCP                     397d
proxy-public                           LoadBalancer   10.100.149.208   XXXXXXX.us-west-2.elb.amazonaws.com   443:31304/TCP,80:30547/TCP   397d
traefik-icesat2-staging-dask-gateway   ClusterIP      10.100.213.17    <none>   
```

```
(binderhub)
NAME                                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                      AGE
api-staging-dask-gateway                ClusterIP      10.100.12.65     <none>                                                                    8000/TCP                     9d
binder                                  LoadBalancer   10.100.86.37     XXXXXXXXXX.com   80:30274/TCP                 9d
hub                                     ClusterIP      10.100.9.121     <none>                                                                    8081/TCP                     9d
kube-lego-nginx                         ClusterIP      10.100.148.52    <none>                                                                    8080/TCP                     9d
proxy-api                               ClusterIP      10.100.125.74    <none>                                                                    8001/TCP                     9d
proxy-public                            LoadBalancer   10.100.177.150   XXXXXXXXXX.us-west-2.elb.amazonaws.com   443:31106/TCP,80:30777/TCP   9d
staging-nginx-ingress-controller        LoadBalancer   10.100.86.217    XXXXXXXXXX.us-west-2.elb.amazonaws.com   80:30754/TCP,443:32543/TCP   9d
staging-nginx-ingress-default-backend   ClusterIP      10.100.113.52    <none>                                                                    80/TCP                       9d
traefik-staging-dask-gateway            LoadBalancer   10.100.76.184    XXXXXXXXXX.us-west-2.elb.amazonaws.com    80:30477/TCP                 9d
```

**Comment by scottyhq** [comment]
Sorry, I think looking into an alternative config might be a red herring, and I suspect https://github.com/pangeo-data/pangeo-cloud-federation/pull/592 broke things with incorrect auth config. I ran a ` helm rollback icesat2-staging 293 -n icesat2-staging` and I can create and scale clusters without error.  

```python
import dask
import yaml
print(yaml.dump(dask.config.config['gateway']))
```

```
address: https://staging.aws-uswest2.pangeo.io/services/dask-gateway
auth:
  type: jupyterhub
cluster:
  options:
    image: '{JUPYTER_IMAGE_SPEC}'
proxy_address: gateway://traefik-icesat2-staging-dask-gateway.icesat2-staging:80
```

**Comment by consideRatio** [comment]
@scottyhq ah yeah you are probably right, for auth like that, the apiKeys is needed like in my setup

**Comment by scottyhq** [comment]
@TomAugspurger, @consideRatio - Still having some issues running code on the new cluster (2020.04.28 pangeo notebook) still has:
```
dask                      2.15.0                     py_0    conda-forge
dask-core                 2.15.0                     py_0    conda-forge
dask-gateway              0.7.1            py37hc8dfbb8_0    conda-forge
dask-glm                  0.2.0                      py_1    conda-forge
dask-kubernetes           0.10.1                     py_0    conda-forge
dask-labextension         2.0.1                      py_0    conda-forge
dask-ml                   1.2.0                      py_0    conda-forge
pangeo-dask               2020.04.28                    0    conda-forge
``` 

`print(yaml.dump(dask.config.config['gateway']))`
```
address: https://staging.aws-uswest2.pangeo.io/services/dask-gateway
auth:
  kwargs: {}
  type: jupyterhub
cluster:
  options:
    image: '{JUPYTER_IMAGE_SPEC}'
http-client:
  proxy: true
proxy_address: gateway://traefik-icesat2-staging-dask-gateway.icesat2-staging:80
public-address: null
```

workers launch but running code fails with `TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None`

```python
def test():
    print('Hello from a dask worker')
client.run(test)
```

Full traceback

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-d41f053d77c5> in <module>
      1 def test():
      2     print('Hello from a dask worker')
----> 3 client.run(test)

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in run(self, function, *args, **kwargs)
   2430         >>> c.run(print_state, wait=False)  # doctest: +SKIP
   2431         """
-> 2432         return self.sync(self._run, function, *args, **kwargs)
   2433 
   2434     def run_coroutine(self, function, *args, **kwargs):

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    778         else:
    779             return sync(
--> 780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )
    782 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    345     if error[0]:
    346         typ, exc, tb = error[0]
--> 347         raise exc.with_traceback(tb)
    348     else:
    349         return result[0]

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in f()
    329             if callback_timeout is not None:
    330                 future = asyncio.wait_for(future, callback_timeout)
--> 331             result[0] = yield future
    332         except Exception as exc:
    333             error[0] = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/client.py in _run(self, function, nanny, workers, wait, *args, **kwargs)
   2359             ),
   2360             workers=workers,
-> 2361             nanny=nanny,
   2362         )
   2363         results = {}

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    748             name, comm.name = comm.name, "ConnectionPool." + key
    749             try:
--> 750                 result = await send_recv(comm=comm, op=key, **kwargs)
    751             finally:
    752                 self.pool.reuse(self.addr, comm)

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    547         if comm.deserialize:
    548             typ, exc, tb = clean_exception(**response)
--> 549             raise exc.with_traceback(tb)
    550         else:
    551             raise Exception(response["text"])

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/core.py in handle_comm()
    401                             result = asyncio.ensure_future(result)
    402                             self._ongoing_coroutines.add(result)
--> 403                             result = await result
    404                     except (CommClosedError, CancelledError) as e:
    405                         if self.status == "running":

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/scheduler.py in broadcast()
   2982 
   2983         results = await All(
-> 2984             [send_message(address) for address in addresses if address is not None]
   2985         )
   2986 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/utils.py in All()
    235     while not tasks.done():
    236         try:
--> 237             result = await tasks.next()
    238         except Exception:
    239 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/scheduler.py in send_message()
   2975         async def send_message(addr):
   2976             comm = await connect(
-> 2977                 addr, deserialize=self.deserialize, connection_args=self.connection_args
   2978             )
   2979             comm.name = "Scheduler Broadcast"

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/core.py in connect()
    226                 with ignoring(TimeoutError):
    227                     comm = await asyncio.wait_for(
--> 228                         future, timeout=min(deadline - time(), 1)
    229                     )
    230                     break

/srv/conda/envs/notebook/lib/python3.7/asyncio/tasks.py in wait_for()
    440 
    441         if fut.done():
--> 442             return fut.result()
    443         else:
    444             fut.remove_done_callback(cb)

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/tcp.py in connect()
    334         self._check_encryption(address, connection_args)
    335         ip, port = parse_host_port(address)
--> 336         kwargs = self._get_connect_args(**connection_args)
    337 
    338         try:

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/tcp.py in _get_connect_args()
    373 
    374     def _get_connect_args(self, **connection_args):
--> 375         ctx = _expect_tls_context(connection_args)
    376         return {"ssl_options": ctx}
    377 

/srv/conda/envs/notebook/lib/python3.7/site-packages/distributed/comm/tcp.py in _expect_tls_context()
    311             "TLS expects a `ssl_context` argument of type "
    312             "ssl.SSLContext (perhaps check your TLS configuration?)"
--> 313             "  Instead got %s" % str(ctx)
    314         )
    315     return ctx

TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
```

**Comment by consideRatio** [comment]
Posting stuff from slack:

```yaml
# gateway.yaml, for the user with a dask-gateway client
gateway:
  # don't set address to https!
  address: http://traefik-dask-gateway.dask-gateway/services/dask-gateway
  public-address: https://jupyter.dsp.sandvik.com/services/dask-gateway
  auth:
    type: jupyterhub
    jupyterhub:
      apiUrl: http://hub.jupyterhub:8081/hub/api
```

```yaml
And, for the jupyterhub auth I also need:
# config.yaml, for dask-gateway
gateway:
  proxyToken: AAAAAAAA
  auth:
    type: jupyterhub
    jupyterhub:
      # A JupyterHub api token for dask-gateway to use. See
      # https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub.
      apiToken: BBBBBBBB
      # JupyterHub's api url.
      apiUrl: http://hub.jupyterhub:8081/hub/api
  prefix: /services/dask-gateway
```

```yaml
# config.yaml, for jupyterhub
hub:
  services:
    # ref: https://jupyterhub.readthedocs.io/en/stable/reference/services.html#properties-of-a-service
    dask-gateway:
      apiToken: BBBBBBBB
      # url will make jupyterhub configure its own proxy to route
      # "/services/dask-gateway" to this destination.
      url: http://traefik-dask-gateway.dask-gateway
```

For your reference, my gateway options is the following, which I found to make most sense from a user + maintainer perspective. By only letting the user choose the amount of cores, I reduce the risk of bad configuration options where the user would configure a single worker pod to use a unsuitable fraction of the available resources on a node, or block lots of CPU availability without needing to.
The 3.2 GB number per core was designed for n1-standard-8 nodes and would allow for having project calico daemonset installed etc on the node, this way, i would fit 8 worker pods on the 8 core node.

I found this to be a sensible mix of giving the user freedom to choose worker pod size without forcing the user to be aware of what hardware is available. A typical bad example avoided with this setup is to request 4 cores exactly, then a 4 core node would not suffice because some overhead required by k8s, and an 8 core node would be used instead, which would only fit 1 single worker!

This config avoids it.

```yaml
# config.yaml, for jupyterhub's helm chart
hub:
  extraConfig:
    cluster-options: |
      # ref: https://gateway.dask.org/cluster-options.html
      from dask_gateway_server.options import Options, Integer, Float, String
      def option_handler(options):
          return {
              "worker_cores": "%f" % int(options.cores) / 10,
              "worker_cores_limit": "%f" % options.cores,
              "worker_memory": "%fG" % 3.2 * options.cores,
          }
      c.Backend.cluster_options = Options(
          Integer("cores", 1, min=1, max=8, label="Worker CPU cores"),
          handler=option_handler,
      )
```
