### ISSUE TITLE
Poor UX when waiting for scheduler node pool to scale up

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/pangeo-cloud-federation#587]
We recently made a dedicated node pool for schedulers (in addition to our node pool for dask workers).

This makes things a bit slower to get a Dask Cluster when a the pangeo cluster has been idle for a while. A user comes along and does

```
gateway = Gateway()
cluster = gateway.new_cluster()  # wait for scheduler node-pool to scale up, pod to be scheduled
cluster.scale(...)  # second wait for worker node-pool to scale up, pods to be scheduled
```

Two things

1. Can we "ping" the scheduler node pool when we start a user pod, triggering a scale up for the pool?
2. Can we provide any feedback on what we're waiting on in the `gateway.new_cluster()` and `cluster.scale(...)`? (cc @jcrist). This seems hard since it's backend specific, and logs from the backend may contain sensitive information. This might also be better solved somewhere like the lab-extension.

**Comment by jcrist** [comment]
> Can we provide any feedback on what we're waiting on in the gateway.new_cluster() and cluster.scale(...)?

This is an open question. This could definitely be handled, but I'm not sure where/how to display this information to the user (if you have thoughts, I'd be interested to hear them). Presumably other `Cluster` implementations have the same issue, so this isn't specific to dask-gateway.

---

Stepping back a bit here, we'd like:

- Dask workers to be run on preemptible nodes
- Dask schedulers and Jupyter notebooks to be run on non-preemptible nodes
- Pods to be packed nicely, so that node pools can scale up/down nicely, reducing costs
- Getting a notebook and a scheduler quickly make things *feel* snappier. Users can't actually do work until they get workers, but since worker allocation happens in the background they're less likely to notice slowdowns (in my experience).

Given the above requirements (which I may have assumed incorrectly), perhaps dask schedulers and notebooks could share the notebook nodes? To aid in packing and speedy scale up, we might also enable some of the JupyterHub scheduling/placeholder options here: https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html.

cc @consideRatio, who likely has some thoughts on this.

**Comment by TomAugspurger** [comment]
Thanks. Your summary is accurate. So I think we can approach it on two fronts

1. Make changes to get a user from cold-start to running Dask cluster as quickly as possible.
2. Make changes to inform the user what's happening in the background by exposing the node-pool / pod status.

We discussed putting the schedulers in the same node-pool as the jupyter notebooks. @jhamman raised some issues at https://github.com/pangeo-data/pangeo-cloud-federation/pull/567#issuecomment-601784900. In the end we decided to go with a separate node pool (but that could be revisited).

**Comment by consideRatio** [comment]
@jcrist I setup a dask-gateway deployment and opted to make the scheduler run alongside the user pods. Related config:

```yaml
gateway:
  backend:
    scheduler:
      # Any extra configuration for the worker pod. Sets
      # `c.KubeClusterConfig.worker_extra_pod_config`.
      extraPodConfig:
        tolerations:
          - key: "hub.jupyter.org_dedicated"
            operator: "Equal"
            value: "user"
            effect: "NoSchedule"
        nodeSelector:
          hub.jupyter.org/node-purpose: user
        schedulerName: myjhubhelmreleasename-user-scheduler
```

---

I think a key question regarding positioning the user schedulers on the same node or a different node may relate to the resource requests for users / schedulers respectively. If you can fit 4 users per node perfectly and a scheduler takes up 0.1 of the user and you suddenly can only fit three, thats not great. I have no experience with the amount of resource requests that the scheduler needs in general etc though, I find it complicated to figure out what makes most sense here.
