### ISSUE TITLE
Posting announcements on hubs

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#595]
I believe jupyterhub has a way to configure custom login messages that are broadcasted to users. We have a couple of big changes coming up (e.g. dask gateway) that we may want to announce loudly. What is the easiest way to allow admins to broadcast such messages?

**Comment by TomAugspurger** [comment]
I believe that this would do it

```yaml
# /deployments/*/config/common.yaml
pangeo:
  jupyterhub:
    hub:
      extraConfig:
        announcements: |
          c.JupyterHub.template_vars = {"announcement": "The message here."}
```

I can try that out on staging later today.
