### ISSUE TITLE
Questions about node pools on the new cluster

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#656]
I have been working with @chiaral on the new cluster, and we have noticed a few things:

### Node pools are not consistently scaling up in response to dask cluster creation

We see a lot of unschedulable pods:

![image](https://user-images.githubusercontent.com/1197350/87354685-f6ea3b00-c52c-11ea-9931-e8b3652674ea.png)

In the old setup, this would trigger the dask node pool to scale up. That is not happening here. It's been in this state for 30 minutes or more.

### Dask does not seem to use preemptible node pools any more

![image](https://user-images.githubusercontent.com/1197350/87354768-1b461780-c52d-11ea-999d-27d7d8631e9f.png)

This could be bad for our bill.

**Comment by TomAugspurger** [comment]
For the unschedulable pods, we need to bump these values I think https://github.com/pangeo-data/pangeo-cloud-federation/blob/d102a424e71a952bfee977d323c39dfc43cc9fdf/deployments/gcp-uscentral1b/autoprovisioning.json#L3-L4 Does that sound right @jhamman?

Not sure about the preemptible nodes yet. I thought if the pod was marked as preemptible they were auto-assigned to the preemptible node pool.

**Comment by TomAugspurger** [comment]
https://github.com/pangeo-data/pangeo-cloud-federation/pull/632 might be fixing the preemptible node issue.

**Comment by jhamman** [comment]
I think we need to drop these lines into the gcp deployment's common.yaml: 

```yaml
  dask-gateway:
    gateway:
      backend:
        worker:
          extraPodConfig:
            tolerations:
              - key: "cloud.google.com/gke-preemptible"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
```

This should help the cluster node pool create node pools that are preemptible.
