### ISSUE TITLE
logging for production clusters

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#72]
We need to decide what to log and how. Ideally we could keep track of

- when each user's notebook pod is running
- when users start and stop dask clusters
- how much file storage they are using

what else?

The default option on google cloud is JupyterHub Logs -> Stackdriver -> BigQuery

**Comment by rabernat** [comment]
Closely related to #60, because the type of auth we use determines what information we can get about users.

**Comment by rabernat** [comment]
I am now using globus auth with ORCID as identity provider on ocean.pangeo.io. It works!

Here is what the secret `staging.yaml` looks like:
```
jupyterhub:
  proxy:
    secretToken: XXX
  auth:
    type: globus
    globus:
      clientId: "XXX"
      clientSecret: "XXX"
      callbackUrl: "https://staging.ocean.pangeo.io/hub/oauth_callback"
      identityProvider: "orcid.org"
```

Username is mapped to orcid ID! 

It works!
