### ISSUE TITLE
A git-crypt symmetric key from the maintainers of this repo ?

### ISSUE THREAD

**Issue by gmaze** [pangeo-data/pangeo-cloud-federation#910]
hi folks ! 
A dummy question, trying/playing to implement a Pangeo hub for my university: 
I wonder who to ask for "a git-crypt symmetric key from the maintainers of this repo (https://github.com/pangeo-data/pangeo-cloud-federation) to be used for your deployment secrets files." ?
(I acknowledge that not answering this myself is not a good indication for this hub reliability ;-)

**Comment by TomAugspurger** [comment]
You shouldn't need access to the decrypted files. But the keys are

```yaml
daskhub:
  jupyterhub:
    proxy:
      secretToken: 
    auth:
      custom:
        config:
          client_id:
          client_secret:
    hub:
      services:
        dask-gateway:
          apiToken:
        mlflow:
          apiToken:

  dask-gateway:
    gateway:
      proxyToken:
      auth:
        type: jupyterhub
        jupyterhub:
          apiToken:
```

The relevant ones are documented in https://github.com/dask/helm-chart/blob/master/daskhub/README.md. The `auth` keys are custom to our authentication setup, and `marlow` is an unrelated jupyterhub service. The final difference is that these are nested under a top-level `daskhub` key` since we're using hubploy to deploy from this repo.
