### ISSUE TITLE
Getting 401 Unauthorized trying to create Dask cluster from Jupyterhub

### ISSUE THREAD

**Issue by saranicole** [pangeo-data/pangeo-cloud-federation#946]
I am using the Pangeo Helm chart to install Jupyterhub with Dask Gateway.  

When I try to create a Dask Gateway using the following code:

```
from dask_gateway import Gateway
gateway = Gateway()
cluster = gateway.new_cluster()
cluster.scale(4)
cluster
```

I get a 401 Unauthorized

```
ClientResponseError: 401, message='Unauthorized', url=URL('http://traefik-pangeo-dask-gateway.dev/services/dask-gateway/api/v1/clusters/')
```

I think this has to do with the authentication tokens provided to the Helm chart, but I am not clear on what their functions are exactly.

My config
```
dask-gateway:
    gateway:
      auth:
        jupyterhub:
          apiToken: <<gateway secret>>
        type: jupyterhub
      proxyToken: <<secret #1>>
jupyterhub:
  auth:
    github:
      callbackUrl: https://pangeo-dev-k8s.research.mydomain.co/hub/oauth_callback
      clientId: <<secret #2>>
      clientSecret: <<secret #3>>
  hub:
    services:
        dask-gateway:
          apiToken: <<gateway secret>>
          url: http://traefik-pangeo-dask-gateway.dev
  proxy:
    secretToken: <<secret #4>>
    https:
        enabled: true
        hosts:
        - pangeo-dev-k8s.research.mydomain.co
        type: offload
    singleuser:
      extraEnv:
        DASK_GATEWAY__ADDRESS: https://traefik-pangeo-dask-gateway.dev/services/dask-gateway/
        DASK_GATEWAY__PROXY_ADDRESS: gateway://traefik-pangeo-dask-gateway.dev:80
```

I understand that the << gateway secret >> has to be the same for the hub.services.dask-gateway.apiToken and dask-gateway.gateway.auth.jupyterhub.apiToken.  What does dask-gateway.gateway.auth.jupyterhub.proxyToken (# 1) authenticate?  How about jupyterhub.proxy.secretToken (# 4) ?  What could be causing the 401 unauthenticated error?

Thanks very much in advance.
